const HOME_SCREEN_BEST_POPULAR_MOVIES_AND_SERIALS = "BEST POPULAR MOVIES AND SERIALS";
const SHOWCASES_TITLE = "SHOWCASES";
const MORE_SHOWCASES_TITLE = "MORE SHOWCASES";
const BEST_ACTORS_TITLE = "BEST ACTORS";
const MORE_ACTORS_TITLE = "MORE ACTORS";

const MOVIE_DETAIL_ACTORS_TITLE = "ACTORS";
const MOVIE_DETAIL_CREATORS_TITLE = "CREATORS";
const MOVIE_DETAIL_MORE_CREATORS_TITLE = "MORE CREATORS";